name: Build SysLoader - Windows Driver Loader

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
        version: 12.2.0
    
    - name: Build EXE
      run: |
        windres resources/icon.rc -O coff -o icon.res
        g++ -O2 -mwindows -std=c++17 -o SysLoader.exe src/main.cpp icon.res -lcomctl32 -ladvapi32 -lshlwapi -luser32 -lgdi32 -lws2_32 -static
    
    - name: Build DLL
      run: |
        g++ -O2 -shared -std=c++17 -o SysLoader.dll src/main.cpp icon.res -D_DLL -lcomctl32 -ladvapi32 -lshlwapi -luser32 -lgdi32 -lws2_32 -static
    
    - name: Create sys.ini
      run: |
        echo "[Settings]" > sys.ini
        echo "Driver=MyDriver.sys" >> sys.ini
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: SysLoader
        path: |
          SysLoader.exe
          SysLoader.dll
          sys.ini
          resources/Loader.sys
