name: Build SysLoader

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: mingw-w64-x86_64-gcc
        update: true
    
    - name: Build EXE
      shell: msys2 {0}
      run: |
        cd src
        g++ -O2 -std=c++17 -o ../SysLoader.exe main.cpp -lcomctl32 -ladvapi32 -lshlwapi -luser32 -lgdi32 -lws2_32 -static -Wl,--subsystem,windows
    
    - name: Build DLL
      shell: msys2 {0}
      run: |
        cd src
        g++ -O2 -shared -std=c++17 -o ../SysLoader.dll main.cpp -D_DLL -lcomctl32 -ladvapi32 -lshlwapi -luser32 -lgdi32 -lws2_32 -static
    
    - name: Create sys.ini
      shell: msys2 {0}
      run: |
        echo "[Settings]" > sys.ini
        echo "Driver=MyDriver.sys" >> sys.ini
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: SysLoader
        path: |
          SysLoader.exe
          SysLoader.dll
          sys.ini
          resources/Loader.sys
